name: hcg-16
channels:
 - conda-forge
 - bioconda
 - defaults
 - conda-forge/label/broken
dependencies:
 - python 3.6.*
 - aplpy 2.0.*
 - astropy 3.1.*
 - cgatcore 0.5.12
 - jupyter
 - matplotlib 3.0.*
 - nbconvert 5.5.*
 - numpy 1.16.*
 - unzip
 - curl
 - udocker 1.3.*
