
# https://arxiv.org/pdf/1710.09145.pdf
FROM kernsuite/base:4

# https://stackoverflow.com/questions/28405902/how-to-set-the-locale-inside-a-ubuntu-docker-container
RUN docker-apt-install locales && locale-gen en_US.UTF-8
ENV LANG=en_US.UTF-8 LANGUAGE=en_US.UTF-8 LC_ALL=en_US.UTF-8

# https://arxiv.org/pdf/1710.09145.pdf
RUN docker-apt-install casalite libcurl4 lsb-core

# https://docs.docker.com/engine/reference/builder/#workdir
RUN mkdir /data
WORKDIR /data

# https://docs.docker.com/develop/develop-images/dockerfile_best-practices/#entrypoint
ENTRYPOINT ["casa"]
CMD ["--help"]

